// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
// */

// import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
// import { useFrame, useLoader } from "@react-three/fiber";
// import { useControls } from "leva";
// import React, { useEffect, useMemo, useRef, useState } from "react";

// import * as THREE from "three";

// const corresponding = {
//   A: "viseme_PP",
//   B: "viseme_kk",
//   C: "viseme_I",
//   D: "viseme_AA",
//   E: "viseme_O",
//   F: "viseme_U",
//   G: "viseme_FF",
//   H: "viseme_TH",
//   X: "viseme_PP",
// };

// export function Avatar({ triggerWelcome, ...props }) {
//   const [playAudio, setPlayAudio] = useState(false);
//   const [script, setScript] = useState("welcome");
//   const whiteMaterial = new THREE.MeshStandardMaterial({
//   color: '#0062ff',
//   transparent: true,
//   opacity: 1,   // Adjust 0 → invisible, 1 → solid
// });

//   const audio = useMemo(() => new Audio(`/audios/${script}.mp3`), [script]);
//   const jsonFile = useLoader(THREE.FileLoader, `audios/${script}.json`);
//   const lipsync = JSON.parse(jsonFile);

//   useFrame(() => {
//     const currentAudioTime = audio.currentTime;
//     if (audio.paused || audio.ended) {
//       setAnimation("Idle");
//       return;
//     }

//     Object.values(corresponding).forEach((value) => {
//       if (!smoothMorphTarget) {
//         nodes.Wolf3D_Head.morphTargetInfluences[
//           nodes.Wolf3D_Head.morphTargetDictionary[value]
//         ] = 0;
//         nodes.Wolf3D_Teeth.morphTargetInfluences[
//           nodes.Wolf3D_Teeth.morphTargetDictionary[value]
//         ] = 0;
//       } else {
//         nodes.Wolf3D_Head.morphTargetInfluences[
//           nodes.Wolf3D_Head.morphTargetDictionary[value]
//         ] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Head.morphTargetInfluences[
//             nodes.Wolf3D_Head.morphTargetDictionary[value]
//           ],
//           0,
//           morphTargetSmoothing
//         );

//         nodes.Wolf3D_Teeth.morphTargetInfluences[
//           nodes.Wolf3D_Teeth.morphTargetDictionary[value]
//         ] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Teeth.morphTargetInfluences[
//             nodes.Wolf3D_Teeth.morphTargetDictionary[value]
//           ],
//           0,
//           morphTargetSmoothing
//         );
//       }
//     });

//     for (let i = 0; i < lipsync.mouthCues.length; i++) {
//       const mouthCue = lipsync.mouthCues[i];
//       if (
//         currentAudioTime >= mouthCue.start &&
//         currentAudioTime <= mouthCue.end
//       ) {
//         if (!smoothMorphTarget) {
//           nodes.Wolf3D_Head.morphTargetInfluences[
//             nodes.Wolf3D_Head.morphTargetDictionary[
//               corresponding[mouthCue.value]
//             ]
//           ] = 1;
//           nodes.Wolf3D_Teeth.morphTargetInfluences[
//             nodes.Wolf3D_Teeth.morphTargetDictionary[
//               corresponding[mouthCue.value]
//             ]
//           ] = 1;
//         } else {
//           nodes.Wolf3D_Head.morphTargetInfluences[
//             nodes.Wolf3D_Head.morphTargetDictionary[
//               corresponding[mouthCue.value]
//             ]
//           ] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Head.morphTargetInfluences[
//               nodes.Wolf3D_Head.morphTargetDictionary[
//                 corresponding[mouthCue.value]
//               ]
//             ],
//             1,
//             morphTargetSmoothing
//           );
//           nodes.Wolf3D_Teeth.morphTargetInfluences[
//             nodes.Wolf3D_Teeth.morphTargetDictionary[
//               corresponding[mouthCue.value]
//             ]
//           ] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Teeth.morphTargetInfluences[
//               nodes.Wolf3D_Teeth.morphTargetDictionary[
//                 corresponding[mouthCue.value]
//               ]
//             ],
//             1,
//             morphTargetSmoothing
//           );
//         }

//         break;
//       }
//     }
//   });

//   useEffect(() => {
//     nodes.Wolf3D_Head.morphTargetInfluences[
//       nodes.Wolf3D_Head.morphTargetDictionary["viseme_H"]
//     ] = 0;
//     nodes.Wolf3D_Teeth.morphTargetInfluences[
//       nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_H"]
//     ] = 0;
//     if (triggerWelcome) {
//     setScript("welcome");
//     setPlayAudio(true);
//     audio.currentTime = 0;
//     audio.play();
//     setAnimation("Greeting");
//   }
// }, [triggerWelcome]);

//   const { nodes, materials } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
//   const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
//   const { animations: angryAnimation } = useFBX(
//     "/animations/Angry Gesture.fbx"
//   );
//   const { animations: greetingAnimation } = useFBX(
//     "/animations/Standing Greeting.fbx"
//   );

//   idleAnimation[0].name = "Idle";
//   angryAnimation[0].name = "Angry";
//   greetingAnimation[0].name = "Greeting";

//   const [animation, setAnimation] = useState("Idle");

//   const group = useRef();
//   const { actions } = useAnimations(
//     [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
//     group
//   );

//   // CODE ADDED AFTER THE TUTORIAL (but learnt in the portfolio tutorial ♥️)
//   useFrame((state) => {
//     if (headFollow) {
//       group.current.getObjectByName("Head").lookAt(state.camera.position);
//     }
//   });

//   return (
//     <group {...props} dispose={null} ref={group}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//        material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//   name="EyeLeft"
//   geometry={nodes.EyeLeft.geometry}
//   material={whiteMaterial}
//   skeleton={nodes.EyeLeft.skeleton}
//   morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//   morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}

// />

// <skinnedMesh
//   name="EyeRight"
//   geometry={nodes.EyeRight.geometry}
//   material={whiteMaterial}
//   skeleton={nodes.EyeRight.skeleton}
//   morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//   morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}

// />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />

//     </group>
//   );
// }

// useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");

// import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
// import { useFrame, useLoader } from "@react-three/fiber";
// import React, { useEffect, useMemo, useRef, useState } from "react";
// import * as THREE from "three";

// const corresponding = {
//   A: "viseme_PP",
//   B: "viseme_kk",
//   C: "viseme_I",
//   D: "viseme_AA",
//   E: "viseme_O",
//   F: "viseme_U",
//   G: "viseme_FF",
//   H: "viseme_TH",
//   X: "viseme_PP",
// };

// export function Avatar({ scriptCommand, ...props }) {
//   const [playAudio, setPlayAudio] = useState(false);
//   const [script, setScript] = useState("welcome");
//   const [animation, setAnimation] = useState("Idle");

//   const whiteMaterial = new THREE.MeshStandardMaterial({
//     color: "#0004ff",
//     transparent: true,
//     opacity: 1,
//   });

//   const { nodes, materials } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
//   const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
//   const { animations: angryAnimation } = useFBX(
//     "/animations/Angry Gesture.fbx"
//   );
//   const { animations: greetingAnimation } = useFBX(
//     "/animations/Standing Greeting.fbx"
//   );

//   idleAnimation[0].name = "Idle";
//   angryAnimation[0].name = "Angry";
//   greetingAnimation[0].name = "Greeting";

//   const group = useRef();
//   const { actions } = useAnimations(
//     [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
//     group
//   );

//   const audio = useMemo(() => new Audio(`/audios/${script}.mp3`), [script]);
//   const jsonFile = useLoader(THREE.FileLoader, `audios/${script}.json`);
//   const lipsync = JSON.parse(jsonFile);

//   // Trigger welcome on "hello"
//   useEffect(() => {
//     if (scriptCommand === "hello" || "Hello") {
//       setScript("HelloGalax");
//       setPlayAudio(true);
//       audio.currentTime = 0;
//       audio.play();
//       setAnimation("Greeting");
//     } else {
//       setPlayAudio(false);
//       audio.pause();
//       setAnimation("Idle");
//     }
//   }, [scriptCommand]);

//   useFrame((state) => {
//     if (!nodes || !audio) return;

//     const delta = state.clock.getDelta();

//     // Head follows camera
//     if (group.current) {
//       group.current.getObjectByName("Head")?.lookAt(state.camera.position);
//     }

//     // Lipsync
//     if (!audio.paused && !audio.ended && lipsyncCues.length > 0) {
//       const currentTime = audio.currentTime;
//       const smoothingFactor = 100;

//       // Reset all morph targets smoothly
//       Object.values(corresponding).forEach((viseme) => {
//         const index = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//         nodes.Wolf3D_Head.morphTargetInfluences[index] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Head.morphTargetInfluences[index],
//           0,
//           1 - Math.exp(-smoothingFactor * delta)
//         );
//         nodes.Wolf3D_Teeth.morphTargetInfluences[index] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Teeth.morphTargetInfluences[index],
//           0,
//           1 - Math.exp(-smoothingFactor * delta)
//         );
//       });

//       // Apply current cue
//       for (let cue of lipsyncCues) {
//         if (currentTime >= cue.start && currentTime <= cue.end) {
//           const viseme = corresponding[cue.value];
//           const index = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//           nodes.Wolf3D_Head.morphTargetInfluences[index] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Head.morphTargetInfluences[index],
//             1,
//             1 - Math.exp(-smoothingFactor * delta)
//           );
//           nodes.Wolf3D_Teeth.morphTargetInfluences[index] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Teeth.morphTargetInfluences[index],
//             0.8,
//             1 - Math.exp(-smoothingFactor * delta)
//           );
//           break; // Only one cue active at a time
//         }
//       }
//     }
//   });

//   return (
//     <group {...props} dispose={null} ref={group}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//         name="EyeLeft"
//         geometry={nodes.EyeLeft.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.EyeLeft.skeleton}
//         morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");




// import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
// import { useFrame, useLoader } from "@react-three/fiber";
// import React, { useEffect, useMemo, useRef, useState } from "react";
// import * as THREE from "three";

// const corresponding = {
//   A: "viseme_PP",
//   B: "viseme_kk",
//   C: "viseme_I",
//   D: "viseme_AA",
//   E: "viseme_O",
//   F: "viseme_U",
//   G: "viseme_FF",
//   H: "viseme_TH",
//   X: "viseme_PP",
// };

// export function Avatar({ scriptCommand, ...props }) {
//   const [playAudio, setPlayAudio] = useState(false);
//   const [script, setScript] = useState("welcome");
//   const [animation, setAnimation] = useState("Idle");

//   const whiteMaterial = new THREE.MeshStandardMaterial({
//     color: "#0004ff",
//     transparent: true,
//     opacity: 1,
//   });

//   const { nodes } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
//   const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
//   const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
//   const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");

//   idleAnimation[0].name = "Idle";
//   angryAnimation[0].name = "Angry";
//   greetingAnimation[0].name = "Greeting";

//   const group = useRef();
//   const { actions } = useAnimations(
//     [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
//     group
//   );

//   const audio = useMemo(() => new Audio(`/audios/${script}.mp3`), [script]);
//   const jsonFile = useLoader(THREE.FileLoader, `audios/${script}.json`);
//   const lipsync = JSON.parse(jsonFile);

//   // Trigger welcome on "hello"
//   useEffect(() => {
//     if (scriptCommand.toLowerCase() === "hello") {
//       setScript("HelloGalax"); // your welcome audio
//       setPlayAudio(true);
//       audio.currentTime = 0;
//       audio.play();
//       setAnimation("Greeting");
//     } else {
//       setPlayAudio(false);
//       audio.pause();
//       setAnimation("Idle");
//     }
//   }, [scriptCommand]);

//   useFrame((state, delta) => {
//     if (!nodes || !audio) return;

//     const lerpSpeed = 0.9;

//     // Head follows camera
//     if (group.current) {
//       group.current.getObjectByName("Head")?.lookAt(state.camera.position);
//     }

//     // Smooth Lipsync
//     if (playAudio && !audio.paused && lipsync.mouthCues.length > 0) {
//       const currentTime = audio.currentTime;

//       // Reset all morph targets smoothly
//       Object.values(corresponding).forEach((viseme) => {
//         const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//         const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

//         nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
//           0,
//           lerpSpeed
//         );
//         nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
//           0,
//           lerpSpeed
//         );
//       });

//       // Apply current cue
//       for (let cue of lipsync.mouthCues) {
//         if (currentTime >= cue.start && currentTime <= cue.end) {
//           const viseme = corresponding[cue.value];
//           const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//           const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

//           nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
//             1,
//             lerpSpeed
//           );
//           nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
//             1.8,
//             lerpSpeed
//           );
//           break; // only one cue at a time
//         }
//       }
//     }

//     // Play current animation
//     if (actions) {
//       Object.values(actions).forEach((action) => action.stop());
//       actions[animation]?.play();
//     }
//   });

//   return (
//     <group {...props} dispose={null} ref={group}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//         name="EyeLeft"
//         geometry={nodes.EyeLeft.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.EyeLeft.skeleton}
//         morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={whiteMaterial}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");




// import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
// import { useFrame, useLoader } from "@react-three/fiber";
// import React, { useEffect, useMemo, useRef, useState } from "react";
// import * as THREE from "three";

// const corresponding = {
//   A: "viseme_PP",
//   B: "viseme_kk",
//   C: "viseme_I",
//   D: "viseme_AA",
//   E: "viseme_O",
//   F: "viseme_U",
//   G: "viseme_FF",
//   H: "viseme_TH",
//   X: "viseme_PP",
// };

// export function Avatar({ scriptCommand, ...props }) {
//   const [playAudio, setPlayAudio] = useState(false);
//   const [script, setScript] = useState("welcome");
//   const [animation, setAnimation] = useState("Idle");

//   // Hologram material
//   const holoMaterial = new THREE.MeshStandardMaterial({
//     color: "#00eaff",
//     transparent: true,
//     opacity: 0.8,
//     roughness: 0.1,
//     metalness: 0.8,
//   });

//   const { nodes } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
//   const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
//   const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
//   const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");

//   idleAnimation[0].name = "Idle";
//   angryAnimation[0].name = "Angry";
//   greetingAnimation[0].name = "Greeting";

//   const group = useRef();
//   const { actions } = useAnimations(
//     [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
//     group
//   );

//   const audio = useMemo(() => new Audio(`/audios/${script}.mp3`), [script]);
//   const jsonFile = useLoader(THREE.FileLoader, `audios/${script}.json`);
//   const lipsync = JSON.parse(jsonFile);

//   // Trigger welcome on "hello"
//   useEffect(() => {
//     if (scriptCommand.toLowerCase() === "hello") {
//       setScript("HelloGalax"); // change to your audio filename
//       setPlayAudio(true);
//       audio.currentTime = 0;
//       audio.play();
//       setAnimation("Greeting");
//     } else {
//       setPlayAudio(false);
//       audio.pause();
//       setAnimation("Idle");
//     }
//   }, [scriptCommand]);

//   useFrame((state) => {
//     if (!nodes || !audio) return;

//     const delta = state.clock.getDelta();
//     const smoothingFactor = 500; // adjust for faster/slower lipsync

//     // Head follows camera
//     if (group.current) {
//       group.current.getObjectByName("Head")?.lookAt(state.camera.position);
//     }

//     // Lipsync
//     if (!audio.paused && !audio.ended && lipsync.mouthCues.length > 0) {
//       const currentTime = audio.currentTime;

//       // Reset all morph targets smoothly
//       Object.values(corresponding).forEach((viseme) => {
//         const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//         const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

//         nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
//           0,
//           1 - Math.exp(-smoothingFactor * delta)
//         );

//         nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
//           0,
//           1 - Math.exp(-smoothingFactor * delta)
//         );
//       });

//       // Apply current cue
//       for (let cue of lipsync.mouthCues) {
//         if (currentTime >= cue.start && currentTime <= cue.end) {
//           const viseme = corresponding[cue.value];
//           const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//           const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

//           nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
//             1,
//             1 - Math.exp(-smoothingFactor * delta)
//           );

//           nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
//             0.8,
//             1 - Math.exp(-smoothingFactor * delta)
//           );
//           break; // only one cue active at a time
//         }
//       }
//     }

//     // Play animation
//     if (actions) {
//       Object.values(actions).forEach((action) => action.stop());
//       actions[animation]?.play();
//     }
//   });

//   return (
//     <group {...props} dispose={null} ref={group}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//         name="EyeLeft"
//         geometry={nodes.EyeLeft.geometry}
//         material={holoMaterial}
//         skeleton={nodes.EyeLeft.skeleton}
//         morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={holoMaterial}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Teeth"
//         geometry={nodes.Wolf3D_Teeth.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Teeth.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");




// import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
// import { useFrame, useLoader } from "@react-three/fiber";
// import React, { useEffect, useRef, useState } from "react";
// import * as THREE from "three";

// const corresponding = {
//   A: "viseme_PP",
//   B: "viseme_kk",
//   C: "viseme_I",
//   D: "viseme_AA",
//   E: "viseme_O",
//   F: "viseme_U",
//   G: "viseme_FF",
//   H: "viseme_TH",
//   X: "viseme_PP",
// };

// export function Avatar({ scriptCommand, ...props }) {
//   const [animation, setAnimation] = useState("Idle");
//   const [audio, setAudio] = useState(null);

//   // Hologram material
//   const holoMaterial = new THREE.MeshStandardMaterial({
//     color: "#00eaff",
//     transparent: true,
//     opacity: 0.8,
//     roughness: 0.1,
//     metalness: 0.8,
//   });

//   const { nodes } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
//   const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
//   const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
//   const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");

//   idleAnimation[0].name = "Idle";
//   angryAnimation[0].name = "Angry";
//   greetingAnimation[0].name = "Greeting";

//   const group = useRef();
//   const { actions } = useAnimations(
//     [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
//     group
//   );

//   // Load lipsync JSON for HelloGalax (always the same)
//   const jsonFile = useLoader(THREE.FileLoader, `/audios/HelloGalax.json`);
//   const lipsync = JSON.parse(jsonFile);

//   // Trigger "hello" command
//   useEffect(() => {
//     if (scriptCommand.toLowerCase() === "hello") {
//       // Stop previous audio if any
//       if (audio) {
//         audio.pause();
//         audio.currentTime = 0;
//       }

//       // Create fresh audio instance
//       const newAudio = new Audio("/audios/HelloGalax.mp3");
//       setAudio(newAudio);
//       newAudio.currentTime = 0;
//       newAudio.play();
//       setAnimation("Greeting");

//       // Cleanup on unmount
//       return () => {
//         newAudio.pause();
//         newAudio.currentTime = 0;
//       };
//     } else {
//       setAnimation("Idle");
//       if (audio) {
//         audio.pause();
//         audio.currentTime = 0;
//       }
//     }
//   }, [scriptCommand]);

//   useFrame((state) => {
//     if (!nodes || !audio) return;

//     const delta = state.clock.getDelta();
//     const smoothingFactor = 500;

//     // Head follows camera
//     group.current?.getObjectByName("Head")?.lookAt(state.camera.position);

//     // Lipsync
//     if (audio && !audio.paused && !audio.ended && lipsync.mouthCues.length > 0) {
//       const currentTime = audio.currentTime;

//       Object.values(corresponding).forEach((viseme) => {
//         const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//         const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

//         nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
//           0,
//           1 - Math.exp(-smoothingFactor * delta)
//         );
//         nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
//           nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
//           0,
//           1 - Math.exp(-smoothingFactor * delta)
//         );
//       });

//       for (let cue of lipsync.mouthCues) {
//         if (currentTime >= cue.start && currentTime <= cue.end) {
//           const viseme = corresponding[cue.value];
//           const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
//           const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

//           nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
//             1,
//             1 - Math.exp(-smoothingFactor * delta)
//           );
//           nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
//             nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
//             0.8,
//             1 - Math.exp(-smoothingFactor * delta)
//           );
//           break;
//         }
//       }
//     }

//     // Play animation
//     if (actions) {
//       Object.values(actions).forEach((action) => action.stop());
//       actions[animation]?.play();
//     }
//   });

//   return (
//     <group {...props} dispose={null} ref={group}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//         name="EyeLeft"
//         geometry={nodes.EyeLeft.geometry}
//         material={holoMaterial}
//         skeleton={nodes.EyeLeft.skeleton}
//         morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={holoMaterial}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Teeth"
//         geometry={nodes.Wolf3D_Teeth.geometry}
//         material={holoMaterial}
//         skeleton={nodes.Wolf3D_Teeth.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");




import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame, useLoader } from "@react-three/fiber";
import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

export function Avatar({ scriptCommand, ...props }) {
  const [animation, setAnimation] = useState("Idle");
  const [audio, setAudio] = useState(null);

  // Hologram material
  const holoMaterial = new THREE.MeshStandardMaterial({
    color: "#00eaff",
    transparent: true,
    opacity: 0.8,
    roughness: 0.1,
    metalness: 0.8,
  });

  const { nodes } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
  const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
  const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
  const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");

  idleAnimation[0].name = "Idle";
  angryAnimation[0].name = "Angry";
  greetingAnimation[0].name = "Greeting";

  const group = useRef();
  const { actions } = useAnimations(
    [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
    group
  );

  // Load lipsync JSON for HelloGalax (always the same)
  const jsonFile = useLoader(THREE.FileLoader, `/audios/HelloGalax.json`);
  const lipsync = JSON.parse(jsonFile);

  // ---- Handle "hello" command ----
 useEffect(() => {
  if (scriptCommand.toLowerCase() === "hello") {
    // Stop previous audio if any
    if (audio) {
      audio.pause();
      audio.currentTime = 0;
    }

    // Create fresh audio instance
    const newAudio = new Audio("/audios/HelloGalax.mp3");
    setAudio(newAudio);
    newAudio.currentTime = 0;
    newAudio.play();

    // Always idle
    setAnimation("Idle");

    return () => {
      newAudio.pause();
      newAudio.currentTime = 0;
    };
  }
}, [scriptCommand]);

  // ---- Frame loop: head, lipsync, animations ----
  useFrame((state) => {
    if (!nodes || !audio) return;
    const delta = state.clock.getDelta();
    const smoothingFactor = 500;

    // Head always looks at camera
    // const head = group.current?.getObjectByName("Head");
    // if (head) {
    //   const cameraPos = state.camera.position.clone();
    //   head.lookAt(cameraPos);
    // }

    // Lipsync
    if (audio && !audio.paused && !audio.ended && lipsync.mouthCues.length > 0) {
      const currentTime = audio.currentTime;

      Object.values(corresponding).forEach((viseme) => {
        const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
        const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

        nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
          nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
          0,
          1 - Math.exp(-smoothingFactor * delta)
        );
        nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
          nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
          0,
          1 - Math.exp(-smoothingFactor * delta)
        );
      });

      for (let cue of lipsync.mouthCues) {
        if (currentTime >= cue.start && currentTime <= cue.end) {
          const viseme = corresponding[cue.value];
          const indexHead = nodes.Wolf3D_Head.morphTargetDictionary[viseme];
          const indexTeeth = nodes.Wolf3D_Teeth.morphTargetDictionary[viseme];

          nodes.Wolf3D_Head.morphTargetInfluences[indexHead] = THREE.MathUtils.lerp(
            nodes.Wolf3D_Head.morphTargetInfluences[indexHead],
            1,
            1 - Math.exp(-smoothingFactor * delta)
          );
          nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth] = THREE.MathUtils.lerp(
            nodes.Wolf3D_Teeth.morphTargetInfluences[indexTeeth],
            0.8,
            1 - Math.exp(-smoothingFactor * delta)
          );
          break;
        }
      }
    }

    // Play animation
    if (actions) {
      Object.values(actions).forEach((action) => action.stop());
      actions[animation]?.play();
    }
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={holoMaterial}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={holoMaterial}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={holoMaterial}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={holoMaterial}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={holoMaterial}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={holoMaterial}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={holoMaterial}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={holoMaterial}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");
